FROM continuumio/miniconda3

CMD ["tail", "-f","/dev/null"]

#
# when you will enter in docker you must do:
# cd /mldl # enter in source directory and check for environment.yml
# conda update -n base -c defaults conda #get latest conda version
# conda env create #create conda env
# conda activate #activate
# conda install jupyterlab -y #install jupiter
# jupyter lab
#
# https://www.machinelearningplus.com/deployment/conda-delete-environment-how-to-remove-a-conda-environment/
# https://code.visualstudio.com/docs/datascience/data-science-tutorial
