FROM continuumio/miniconda3

CMD ["tail", "-f","/dev/null"]

#
# when you will enter in docker you must do:
# cd /mldl # enter in source directory and check for environment.yml
# conda env create #create conda env
# conda activate #activate
# python --version #testing python version
#
